version: '3.2'
services:
  samba:
    image: samba-ad-dc:latest
    privileged: true
    hostname: dc1

    container_name: dc1
    dns:
     - 127.0.0.1
    environment:
      SAMBA_DOMAIN: example
      SAMBA_REALM: example.local
    volumes:
      - ./samba:/var/lib/samba        
    ports:
            #    - 53:53
            #      - 53:53/udp
            #      - 88:88
            #      - 88:88/udp
            #      - 135:135
            #      - 139:139
      - 389:389
      - 389:389/udp
        #      - 445:445
        #      - 464:464
        #      - 464:464/udp
        #      - 636:636
        #      - 3268-3269:3268-3269
